"use client";
import { useEffect, useState } from "react";
import { Inbox, Building2, Users, Calendar } from "lucide-react";
import { StatCard } from "@/components/dashboard/stat-card";
const TC:Record<string,string>={contact:"bg-blue-500/20 text-blue-400",showing:"bg-emerald-500/20 text-emerald-400",seller:"bg-purple-500/20 text-purple-400","agent-application":"bg-orange-500/20 text-orange-400","agent-contact":"bg-cyan-500/20 text-cyan-400"};
const STC:Record<string,string>={new:"bg-yellow-500/20 text-yellow-400",contacted:"bg-blue-500/20 text-blue-400",qualified:"bg-emerald-500/20 text-emerald-400",closed:"bg-white/10 text-white/50"};
function frt(d:string):string{const ms=Date.now()-new Date(d).getTime();const m=Math.floor(ms/60000);if(m<1)return"just now";if(m<60)return m+"m ago";const h=Math.floor(m/60);if(h<24)return h+"h ago";const dy=Math.floor(h/24);return dy<30?dy+"d ago":Math.floor(dy/30)+"mo ago";}
interface S{leads:number;newLeads:number;properties:number;agents:number;showings:number;}
interface RL{id:string;first_name:string;last_name:string;type:string;status:string;created_at:string;}
export default function DashboardOverview(){
  const [stats,setStats]=useState<S|null>(null);const [leads,setLeads]=useState<RL[]>([]);const [loading,setLoading]=useState(true);
  useEffect(()=>{(async()=>{try{const [lr,pr,ar,nr,sr]=await Promise.all([fetch("/api/leads?limit=5"),fetch("/api/properties?limit=1"),fetch("/api/agents"),fetch("/api/leads?status=new&limit=1"),fetch("/api/leads?type=showing&limit=1")]);const [ld,pd,ad,nd,sd]=await Promise.all([lr.json(),pr.json(),ar.json(),nr.json(),sr.json()]);setStats({leads:ld.count??0,newLeads:nd.count??0,properties:pd.count??0,agents:ad.data?.length??0,showings:sd.count??0});setLeads(ld.data??[]);}catch{setStats({leads:0,newLeads:0,properties:0,agents:0,showings:0});}finally{setLoading(false);}})();},[]);
  return(<div className="space-y-8"><div><h1 className="text-2xl font-bold text-off-white lg:text-3xl">Dashboard Overview</h1><p className="mt-1 text-sm text-off-white/50">Manage your leads, properties, and agents.</p></div>
    <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{loading?[1,2,3,4].map(i=>(<div key={i} className="h-[132px] animate-pulse rounded-xl border border-white/10 bg-[#1E1E32]"/>)):(<><StatCard title="Total Leads" value={stats?.leads??0} icon={Inbox} change={stats?.newLeads?`+${stats.newLeads} new`:undefined} href="/dashboard/leads"/><StatCard title="Properties" value={stats?.properties??0} icon={Building2} href="/dashboard/properties"/><StatCard title="Agents" value={stats?.agents??0} icon={Users} href="/dashboard/agents"/><StatCard title="Showings" value={stats?.showings??0} icon={Calendar} href="/dashboard/calendar"/></>)}</div>
    <div className="rounded-xl border border-white/10 bg-[#1E1E32]"><div className="flex items-center justify-between border-b border-white/5 px-5 py-4"><h2 className="font-heading text-lg font-semibold text-off-white">Recent Leads</h2><a href="/dashboard/leads" className="text-xs font-medium text-gold hover:text-gold-light transition-colors">View all &rarr;</a></div>
      {loading?<div className="divide-y divide-white/5">{[1,2,3].map(i=>(<div key={i} className="h-12 animate-pulse bg-white/[0.02]"/>))}</div>:leads.length===0?<p className="px-5 py-8 text-center text-sm text-off-white/40">No leads yet.</p>:(<div className="divide-y divide-white/5">{leads.map(l=>(<div key={l.id} className="flex items-center justify-between px-5 py-3"><div className="flex items-center gap-3"><span className="text-sm font-medium text-off-white">{l.first_name} {l.last_name}</span><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider ${TC[l.type]??""}`}>{l.type}</span></div><div className="flex items-center gap-3"><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider ${STC[l.status]??""}`}>{l.status}</span><span className="text-xs text-off-white/40">{frt(l.created_at)}</span></div></div>))}</div>)}
    </div></div>);
}
